default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: hogwarts_development

test:
  <<: *default
  adapter: postgresql
  database: hogwarts_test

production:
  <<: *default
  adapter: postgresql
  database: hogwarts_production
